name: Publish Website

on:
  push:
    branches:
      - master # master 브랜치에 푸시될 때 트리거
  workflow_dispatch: # 수동 실행 허용

jobs:
  Publish-Website:
    name: Publish React Build to WordPress
    runs-on: ubuntu-latest
    steps:
      # 1. GitHub 저장소의 코드를 가져옴
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. React 프로젝트 빌드
      - name: Install dependencies and build React app
        run: |
          cd main
          npm install
          npm run build

      # 4. 빌드된 파일 업로드
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: wpcom
          path: |
            main/build # main 폴더의 build 디렉토리만 업로드